//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboneUcret
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AboneUcret()
        {
            this.Abonelikler = new HashSet<Abonelikler>();
        }
    
        public int AboneUcretID { get; set; }
        public Nullable<int> AboneSuresi { get; set; }
        public string AboneAracTuru { get; set; }
        public Nullable<decimal> AboneUcret1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonelikler> Abonelikler { get; set; }
    }
}
