//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracKapasitesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AracKapasitesi()
        {
            this.OtoparkDurumu = new HashSet<OtoparkDurumu>();
        }
    
        public int KapasiteID { get; set; }
        public Nullable<int> OtomobilKapasitesi { get; set; }
        public Nullable<int> KamyonetKapasitesi { get; set; }
        public Nullable<int> MinibusKapasitesi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtoparkDurumu> OtoparkDurumu { get; set; }
    }
}
