//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracCikis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AracCikis()
        {
            this.Rapor = new HashSet<Rapor>();
        }
    
        public int CikisID { get; set; }
        public string Plaka { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public Nullable<decimal> ToplamUcret { get; set; }
        public string OdemeTuru { get; set; }
        public string DogrulamaKodu { get; set; }
        public Nullable<int> UcretsizGirisID { get; set; }
        public Nullable<int> AracUcretID { get; set; }
        public Nullable<int> AboneID { get; set; }
        public Nullable<int> GirisID { get; set; }
    
        public virtual Abonelikler Abonelikler { get; set; }
        public virtual AracGiris AracGiris { get; set; }
        public virtual AracUcretleri AracUcretleri { get; set; }
        public virtual UcretsizGiris UcretsizGiris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rapor> Rapor { get; set; }
    }
}
