//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracGiris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AracGiris()
        {
            this.AracCikis = new HashSet<AracCikis>();
            this.ParkYeri1 = new HashSet<ParkYeri>();
            this.Rapor = new HashSet<Rapor>();
        }
    
        public int GirisID { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public string Plaka { get; set; }
        public string AracTuru { get; set; }
        public Nullable<int> TelefonNo { get; set; }
        public string DogrulamaKodu { get; set; }
        public string ParkYeri { get; set; }
        public System.DateTime GirisTarihi { get; set; }
        public Nullable<int> UcretsizGirisID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracCikis> AracCikis { get; set; }
        public virtual UcretsizGiris UcretsizGiris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkYeri> ParkYeri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rapor> Rapor { get; set; }
    }
}
