//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rapor
    {
        public Nullable<int> OtoparkID { get; set; }
        public Nullable<int> GirisID { get; set; }
        public Nullable<int> CikisID { get; set; }
        public Nullable<int> ToplamUcret { get; set; }
        public int RaporID { get; set; }
    
        public virtual AracCikis AracCikis { get; set; }
        public virtual AracGiris AracGiris { get; set; }
        public virtual OtoparkDurumu OtoparkDurumu { get; set; }
    }
}
